### ISSUE TITLE
Gives me this upon start

### ISSUE THREAD

**Issue by dvdcd** [nations/spoticord#10]
```
 C:\Users\Dvdcd\Downloads\spoticord-master>node app.js
C:\Users\Dvdcd\Downloads\spoticord-master\app.js:18
async function checkSpotify() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by kalebmmm** [comment]
Outdated nodejs version

**Comment by dvdcd** [comment]
got it, thanks! but now i get this: 
```
module.js:538
    throw err;
    ^

Error: Cannot find module 'discord-rpc'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Dvdcd\Downloads\spoticord-master\app.js:1:82)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by Wist9063** [comment]
you need to install the deps 
do
`npm install`
in the folder that you have the file

**Comment by Phineas** [comment]
Did you manage to get it to work?
