### ISSUE TITLE
App.js not working.

### ISSUE THREAD

**Issue by ghost** [nations/spoticord#13]
Hey there. I am trying to run spoticord but it will not run. All necessary programs (NodeJS, etc) are installed and up-to-date. Here is the error: (I run Arch Linux, x86_64)

`module.js:544
    throw err;
    ^

Error: Cannot find module './util'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/minozen/spoticord/node_modules/discord-rpc/src/index.js:2:14)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)`

**Comment by cernodile** [comment]
Fix;
`npm I devsnek/discord-rpc`, seems like one in npm is bugged, but git fixed.

**Comment by ghost** [comment]
Cannot try now, will try ASAP. Thanks.

**Comment by ghost** [comment]
Worked just fine, thanks cernodile! Closing issue now.

**Comment by ghost** [comment]
New error.

(node:2963) Warning: N-API is an experimental feature and could change at any time.
(node:2963) ExperimentalWarning: The http2 module is an experimental API.
[16:52:29] Error: connection timeout
    at Timeout.setTimeout [as _onTimeout] (/home/minozen/Desktop/spoticord/node_modules/discord-rpc/src/Client.js:110:47)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)

**Comment by cernodile** [comment]
@Minozen I sense a pirate here... Please remove open.spotify.com from your /etc/hosts file!
EDIT: Okay, my fault, it seems like the `npm` package is bugged, please type in `npm i devsnek/discord-rpc`. Sincere apologies for accusing you of being a pirate.
