### ISSUE TITLE
Local files cause the application to crash.

### ISSUE THREAD

**Issue by Aria-NL** [nations/spoticord#21]
C:\Users\*user*\Documents\spoticord-master\app.js:30
    var song = {uri: res.track.track_resource.uri, name: res.track.track_resource.name, album: res.track.album_resource.name, artist: res.track.artist_resource.name, start, end};
                                                                                                                        ^

TypeError: Cannot read property 'name' of undefined
    at C:\Users\*user*\Documents\spoticord-master\app.js:30:121
    at Request._callback (C:\Users\*user*\Documents\spoticord-master\spotify.js:59:16)
    at Request.self.callback (C:\Users\*user*\Documents\spoticord-master\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\*user*\Documents\spoticord-master\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\*user*\Documents\spoticord-master\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)

**Comment by Phineas** [comment]
Fixed. #25
