### ISSUE TITLE
Failed to fetch Spotify data

### ISSUE THREAD

**Issue by Cardinite** [nations/spoticord#22]
```
[01:51:05] Connected to Discord! (385061381344591872)
```
Followed by:
```
[01:51:07] Failed to fetch Spotify data: { err:
   { Error: Command failed: wmic process list /format:csv
Invalid XML content.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
     killed: false,
     code: 44213,
     signal: null,
     cmd: 'wmic process list /format:csv' },
  msg: 'unable to enumerate processes' }
```

First off, thanks for the awesome work on Spoticord! I and a few others seem to be having this issue, any idea what it could be? Running into it with both the latest version of Spotify, v1.0.63.399, and v1.0.20.101.

**Comment by cernodile** [comment]
Hello!
Are you running Windows? If so, check the troubleshooting section of README.md

**Comment by Cardinite** [comment]
Thanks, I didn't think the readme directions applied to this error. Works perfectly. :)
