### ISSUE TITLE
Not sure if it's a bug or not, but when you have "Hide activity" on Spotify, RP does not work.

### ISSUE THREAD

**Issue by Taarek** [nations/spoticord#23]
It throws this error if you have "Hide activity" checked.

```TypeError: Cannot read property 'track_resource' of undefined
    at C:\Users\Tarek\spoticord\app.js:38:19
    at Request._callback (C:\Users\Tarek\spoticord\spotify.js:59:16)
    at Request.self.callback (C:\Users\Tarek\spoticord\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Tarek\spoticord\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Tarek\spoticord\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)```

**Comment by cernodile** [comment]
You left out the error itself. I don't think it's possible to do anything about it though other than creating a fallback saying "you're hiding your activity".

**Comment by jonimettala** [comment]
I'd find it much user friendlier to handle the error properly and throw message like "Your Spotify session can't be private in order to use SpotiCord".
