### ISSUE TITLE
Error seconds after doing node app.js

### ISSUE THREAD

**Issue by ghost** [nations/spoticord#26]
C:\Users\Owner\Desktop\DiscordBots\SpotifyDiscord\spoticord\app.js:50
    var song = {uri: res.track.track_resource.uri, name: res.track.track_resource.name, album: res.track.album_resource.name, artist: res.track.artist_resource.name, start, end, playing: res.playing};
                                                                                                                        ^

TypeError: Cannot read property 'name' of undefined
    at C:\Users\Owner\Desktop\DiscordBots\SpotifyDiscord\spoticord\app.js:50:121
    at Request._callback (C:\Users\Owner\Desktop\DiscordBots\SpotifyDiscord\spoticord\spotify.js:59:16)
    at Request.self.callback (C:\Users\Owner\Desktop\DiscordBots\SpotifyDiscord\spoticord\node_modules\request\request.js:186:22)
    at emitTwo (events.js:135:13)
    at Request.emit (events.js:224:7)
    at Request.<anonymous> (C:\Users\Owner\Desktop\DiscordBots\SpotifyDiscord\spoticord\node_modules\request\request.js:1163:10)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at IncomingMessage.<anonymous> (C:\Users\Owner\Desktop\DiscordBots\SpotifyDiscord\spoticord\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:322:30)

**Comment by cernodile** [comment]
This is now resolved after the latest PR. Enjoy!
