### ISSUE TITLE
unexpected token function

### ISSUE THREAD

**Issue by Baecon** [nations/spoticord#29]
C:\Users\aaa\Desktop\spoticord\app.js:30
async function checkSpotify() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by cernodile** [comment]
Your node version isn't 8.0 or higher. This is clearly stated in the [README.md](https://github.com/nations/spoticord/blob/master/README.md#dependencies)

**Comment by Baecon** [comment]
yeaaaaaa... i just thought about it. "hmmm ive had npm and node installed for a while now maybe thats y it isnt working" im a fucking idiot LuL. was just updating everything right when i saw this
