### ISSUE TITLE
wintools exceeds maxBuffer (w/ fix)

### ISSUE THREAD

**Issue by ndarville** [nations/spoticord#32]
Windows 10, cmd.

## Error ##

```
[17:25:03] Failed to fetch Spotify data: { err: { Error: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:324:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:249:13)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at Pipe.onread (net.js:587:20) cmd: 'wmic process list /format:csv' },
  msg: 'unable to enumerate processes' }
```

## Fix ##

Changing `node_modules/wintools/ps.js` like so fixed it: <https://github.com/anodejs/node-wintools/commit/624c3cbf94e8dda35b03bd048f21f59b2b43258f>

## Solution ##

See if a different package version of `wintools` fixes it or replace the package with [`node-wintools`](https://github.com/anodejs/node-wintools) instead of `wintools` instead.

Via nadavbar/node-spotify-webhelper#6.

**Comment by Phineas** [comment]
node-wintools is wintools on npm

**Comment by gdude2002** [comment]
I can confirm this fix.
