### ISSUE TITLE
Conection timeout when running node app.js

### ISSUE THREAD

**Issue by 7832ru** [nations/spoticord#41]
I keep getting a timeout error when running app.js, everything was fine earlier. I don't know what happened

```
[21:13:11] Error: connection timeout
    at Timeout.setTimeout [as _onTimeout] (C:\Users\lechi\Desktop\Spoticord\spoticord\node_modules\discord-rpc\src\Client.js:109:47)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
```

**Comment by cernodile** [comment]
This seems like a discord-rpc issue, please report it to devsnek/discord-rpc
