### ISSUE TITLE
wmic error

### ISSUE THREAD

**Issue by xxCoolxx18** [nations/spoticord#45]
Getting this when i type Node app.js at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
     killed: false,
     code: 1,
     signal: null,
     cmd: 'wmic process list /format:csv' },
  msg: 'unable to enumerate processes' }
[23:41:50] Failed to fetch Spotify data: { err:
   { Error: Command failed: wmic process list /format:csv
'wmic' is not recognized as an internal or external command,
operable program or batch file.

**Comment by xxCoolxx18** [comment]
Fixed, will close issue.
