### ISSUE TITLE
async function spotifyReconnect () {

### ISSUE THREAD

**Issue by XxPoNaGeXx** [nations/spoticord#54]
async function spotifyReconnect () {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

**Comment by exe** [comment]
Make sure you're using the latest version of Node for async to work correctly.

**Comment by ente3000** [comment]
just mirroring this here, as I already said @ #50, this does not work using the latest node version (9.3.0).

![](https://camo.githubusercontent.com/74ca0b8d7b287109f504e45dee48be5bcdb2e2c4/68747470733a2f2f692e696d6775722e636f6d2f385745486235392e706e67)

**Comment by TheLastZombie** [comment]
I found a way to get around this. [See my comment on a previous issue.](https://github.com/nations/spoticord/issues/50#issuecomment-355829655)

**Comment by cernodile** [comment]
async isn't supported in older versions of node, please update your node version.
