### ISSUE TITLE
Failed to fetch Spotify data:

### ISSUE THREAD

**Issue by zachlmao** [nations/spoticord#62]
Failed to fetch Spotify data: { Error: getaddrinfo ENOENT open.spotify.com:80
    at Object._errnoException (util.js:1026:11)
    at errnoException (dns.js:58:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'open.spotify.com',
  host: 'open.spotify.com',
  port: 80 }

Help?

**Comment by cernodile** [comment]
Hello, have you by any chance blocked `open.spotify.com` via your hosts file. Can you even go there with your browser. If you are using custom DNS servers, please change them else contact your ISP.

**Comment by patriotaki** [comment]
same problem here on my driverrs/etc/host file nothing for spotify

**Comment by kz-n** [comment]
Same problem here on Manjaro
