### ISSUE TITLE
Some sort of "Rebuild" Issue I think...

### ISSUE THREAD

**Issue by DJDEADWOLF** [nations/spoticord#76]
So basically after I type the command "npm i" this happens and I don't have a clue what to do xD

 ref@1.3.5 install C:\Users\Matthew\Desktop\Desktop Files\spoticord\spoticord\spoticord\node_modules\discord-rpc\node_modules\discord.js\node_modules\node-opus\node_modules\ogg-packet\node_modules\ref-struct\node_modules\ref
 node-gyp rebuild

C:\Users\Matthew\Desktop\Desktop Files\spoticord\spoticord\spoticord\node_modules\discord-rpc\node_modules\discord.js\node_modules\node-opus\node_modules\ogg-packet\node_modules\ref-struct\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Matthew\Desktop\Desktop Files\spoticord\spoticord\spoticord\node_modules\discord-rpc\node_modules\discord.js\node_modules\node-opus\node_modules\ogg-packet\node_modules\ref-struct\node_modules\ref
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing ogg-packet@1.0.0

node-opus@0.2.7 install C:\Users\Matthew\Desktop\Desktop Files\spoticord\spoticord\spoticord\node_modules\discord-rpc\node_modules\discord.js\node_modules\node-opus
 node-gyp rebuild

C:\Users\Matthew\Desktop\Desktop Files\spoticord\spoticord\spoticord\node_modules\discord-rpc\node_modules\discord.js\node_modules\node-opus>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Matthew\Desktop\Desktop Files\spoticord\spoticord\spoticord\node_modules\discord-rpc\node_modules\discord.js\node_modules\node-opus
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! node-opus@0.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-opus@0.2.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-opus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-opus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Matthew\Desktop\Desktop Files\spoticord\spoticord\spoticord\npm-debug.log
**===**

**Comment by JackKellyBayliss** [comment]
The debug log above shows that the installation cannot find the python executable so you either need to install it or re-install it.

**Comment by DJDEADWOLF** [comment]
Welp, it's now showing something different about Net framework v4 which I already have?


C:\Users\Matthew\Desktop\Desktop Files\spoticord\spoticord\node_modules\discord-rpc\node_modules\discord.js\node_modules\node-opus>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\Matthew\Desktop\Desktop Files\spoticord\spoticord\node_modules\discord-rpc\node_modules\discord.js\node_modules\node-opus\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Matthew\Desktop\Desktop Files\spoticord\spoticord\node_modules\discord-rpc\node_modules\discord.js\node_modules\node-opus
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! node-opus@0.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-opus@0.2.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-opus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-opus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Matthew\Desktop\Desktop Files\spoticord\spoticord\npm-debug.log
