### ISSUE TITLE
eror 4058 

### ISSUE THREAD

**Issue by ghost** [nations/spoticord#81]
Error: spawn C:\Users\uronow\AppData\Roaming\Spotify\Data\SpotifyWebHelper.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\uronow\\AppData\\Roaming\\Spotify\\Data\\SpotifyWebHelper.exe',
  path: 'C:\\Users\\uronow\\AppData\\Roaming\\Spotify\\Data\\SpotifyWebHelper.exe',
  spawnargs: []
}

**Comment by ErrorRaffyline0** [comment]
got the same issue

**Comment by ErrorRaffyline0** [comment]
The program fails to find Spotify because it is no longer located in 
### C:\Users\[username]\AppData\Roaming\Spotify\Data\SpotifyWebHelper.exe
but rather in
### C:\Users\[username]\AppData\Roaming\Spotify\Spotify.exe
I might make a fork to fix this if it's as simple as just modifying the path.

**Comment by LitePenguins** [comment]
> got the same issue

This project is deprecated, Discord [now has this built in](https://support.discord.com/hc/en-us/articles/360000167212).

**Comment by ErrorRaffyline0** [comment]
> > got the same issue
> 
> This project is deprecated, Discord [now has this built in](https://support.discord.com/hc/en-us/articles/360000167212).

I am aware. Personally I like to still use this method to bypass the need for account linking, because account linking causes Discord to display any track playing on my Spotify account, instead of just the tracks that my PC is playing. Considering I have other people that use my Spotify account, linking my accounts isn't that great of an option.

**Comment by ghost** [comment]
> > > got the same issue
> > 
> > 
> > This project is deprecated, Discord [now has this built in](https://support.discord.com/hc/en-us/articles/360000167212).
> 
> I am aware. Personally I like to still use this method to bypass the need for account linking, because account linking causes Discord to display any track playing on my Spotify account, instead of just the tracks that my PC is playing. Considering I have other people that use my Spotify account, linking my accounts isn't that great of an option.

we can use spotifys api
